site_name: Source

site_description: –ú–∞—Ç–µ—Ä–∏–∞–ª—ã –¥–ª—è –∏–∑—É—á–µ–Ω–∏—è –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è, –ø–æ–¥–≥–æ—Ç–æ–≤–∫–∏ –∫ —Å–æ–±–µ—Å–µ–¥–æ–≤–∞–Ω–∏—è–º
site_author: K
site_url: https://kqkqkqkqkq.github.io/source

# Repository
repo_name: kqkqkqkqkq/source
repo_url: https://github.com/kqkqkqkqkq/source
edit_uri: ""

copyright: Copyright &copy; 2025-2026 K

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/code-tags
  features:
   - navigation.expand

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kqkqkqkqkq/source
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# nav:
#   - '–í–≤–µ–¥–µ–Ω–∏–µ': index.md
#   - '–ó–Ω–∞–∫–æ–º—Å—Ç–≤–æ —Å aiogram': quickstart.md
#   - '–†–∞–±–æ—Ç–∞ —Å —Å–æ–æ–±—â–µ–Ω–∏—è–º–∏': messages.md
#   - '–ö–Ω–æ–ø–∫–∏': buttons.md
#   - '–†–æ—É—Ç–µ—Ä—ã. –°—Ç—Ä—É–∫—Ç—É—Ä–∞': routers.md
#   - '–§–∏–ª—å—Ç—Ä—ã –∏ –º–∏–¥–ª–≤–∞—Ä–∏': filters-and-middlewares.md
#   - '–û—Å–æ–±—ã–µ –∞–ø–¥–µ–π—Ç—ã': special-updates.md
#   - '–ö–æ–Ω–µ—á–Ω—ã–µ –∞–≤—Ç–æ–º–∞—Ç—ã': fsm.md
#   - '–ò–Ω–ª–∞–π–Ω-—Ä–µ–∂–∏–º': inline-mode.md
#   - '–ü–ª–∞—Ç–µ–∂–∏': payments.md
#   - 'üîí –ü—Ä–æ–¥–≤–∏–Ω—É—Ç—ã–π —É—Ä–æ–≤–µ–Ω—å': advanced-teaser.md
# #  - '–î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–µ —á—Ç–µ–Ω–∏–µ':
#    - '–¢–µ—Å—Ç': extra/test.md

nav:
  - –ì–ª–∞–≤–Ω–∞—è: index.md
  - –ê–ª–≥–æ—Ä–∏—Ç–º—ã: algorithms.md


plugins:
  - search:
      lang:
        - en
        - ru
